### ISSUE TITLE
Pre-trained Model can not download,could you upload it again?  Thanks

### ISSUE THREAD

**Issue by sudabai666** [kychern/FacialRetargeting#8]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/18134772/151162004-4461fb00-7a19-4e53-93c6-83fa402beaf4.png">

**Comment by kychern** [comment]
Hi, the download link has been revised, please check it by: https://drive.google.com/file/d/1vuqaK54O3JkmrKwMCOqvSNP5axbzy0Ik/view?usp=sharing
